### ISSUE TITLE
audit 2026-06-12: engine fidelity bugs, broken mocknvml test harness, security hygiene

### ISSUE THREAD

**Issue by ArangoGutierrez** [NVIDIA/k8s-test-infra#393]
Findings from the 2026-06-12 full audit + manual test sweep of main (`f65e41b6`, post-v0.2.0). Docs drift is tracked separately in #384 (re-verified today: only the `demo.sh` mapfile item is fixed, via #385). Everything below is new or newly confirmed. Verification context: unit/race/lint/govulncheck/helm-unittest green, full 7-profile e2e green, all four demos + quickstart + examples manually re-tested by agents (pass, modulo items below).

## A. Engine fidelity bugs (found by running documented examples)

- [ ] `nvmlDeviceGetHandleByUUID` returns SUCCESS for a nonexistent UUID; should be NOT_FOUND. The bridge test for this exists (`tests/mocknvml` `boundary/uuid_invalid`) and fails once the harness build is fixed (item B1).
- [ ] Sparse `power:` configs render garbage instead of N/A: with only `default_limit_mw` set, `nvidia-smi` table shows cap `0W`, and `-q -d POWER` shows `Default Power Limit: unknown return value: 1431655765` (0x55555555 sentinel leaks), `Min 5287.94 W`, `Max 2139062.25 W`, `Average Power Draw 1.00 W`. Unset power-management fields should map to N/A (or derive from `default_limit_mw`). Affects docs/examples.md `single-gpu.yaml` and `gpu-under-load.yaml`.
- [ ] `processes:` blocks in YAML configs are parsed but rendered zeroed (`Process ID: 0, Name: <empty>, Used GPU Memory: 0 MiB`); the examples.md `gpu-under-load.yaml` documents them as working. Note overlap with #381, which implements per-device processes properly — landing #381 likely closes this.

## B. Test infrastructure

- [ ] `tests/mocknvml/Dockerfile:41` builds `main.go` in file-list mode, so `make test` has been broken since #269 added `bridge_tests.go` (`undefined: runBridgeTests`). Fix: `go build -o mocknvml-test .`. No CI workflow runs `tests/mocknvml`, so nothing caught it — consider adding it to the e2e or golang workflow.
- [ ] Root `Makefile` `verify` target runs `gofmt -w -l -d` over ALL `.go` files: it (a) includes `vendor/` (fails on upstream formatting of gopkg.in/yaml.v3 etc.) and (b) WRITES while claiming to verify (`-w`). Should be `-l -d` only, excluding vendor. Several non-vendor files on main also carry gofmt drift (engine/config*.go), invisible because CI only runs golangci-lint.

## C. Security / supply-chain hygiene

- [ ] trivy on `ghcr.io/nvidia/nvml-mock:0.2.0`: 45 CRITICAL/HIGH — 17 from the bundled `kubectl` v1.32.0 binary (old Go stdlib; bump to a current patch release + refresh its sha256 in `deployments/nvml-mock/Dockerfile:70-75`), 28 from debian 12.14 base packages (rebuild picks up current bookworm; triage remainder with `--ignore-unfixed`). Our own Go binaries: 0 findings.
- [ ] Go version stragglers (also #384): `deployments/nvml-mock/Dockerfile` ARG 1.26.0, `pkg/gpu/mocknvml/Makefile:17` 1.25.0, `nvml-mock-e2e.yaml` dispatch default '1.25' — bump all to track `hack/golang-version.sh` (1.26.4).
- [ ] gosec (high severity, medium+ confidence): 103 findings = 101x G115 integer conversions (CGo bridge C<->Go churn — triage once, then suppress per-site or via config) + 2x G404 math/rand (fine for mock jitter; add `#nosec` with justification).
- [ ] `nvml-mock-publish.yaml` signs/attests the image by TAG (`head -1` of tags) while the SBOM step already uses `steps.build.outputs.digest` — sign by digest for consistency with the chart flow (#388).
- [ ] Branch protection on main has `allow_force_pushes: enabled` — consider disabling.
- [ ] `deployments/nvml-mock/Dockerfile` base images are tag-pinned, not digest-pinned (`golang:*-bookworm`, `debian:bookworm-slim`).
- [ ] `.github/workflows/stale.yaml:21` `actions/stale@v10` is the only non-SHA-pinned action.
- [ ] `nvml-mock-e2e.yaml` ibping-multinode job pins `actions/checkout@de0fac2e` (v6.0.2) while the rest of the repo is on `df4cb1c0` (came in with #367 after the #382 bump; dependabot will catch it next cycle).
- [ ] REUSE.toml globs miss `**/Makefile`, `**/Dockerfile`, `**.c` (root-level globs only); `pkg/gpu/mocknvml/Makefile` and `deployments/nvml-mock/Dockerfile` carry old-style boilerplate without SPDX tags.

## D. CHANGELOG gaps

- [ ] The `[0.2.0]` section omits several features that landed in v0.1.0..v0.2.0: dynamic metrics (#323), GPU failure injection (#328), ComputeDomain / fabric / fake-IMEX (#337, #342), toolkit-ready marker (#346). Amend the section (changelog is docs) and `gh release edit` the v0.2.0 notes to match.
- [ ] `[Unreleased]` is empty: #390 (helm push retry) and #391 (tag-publish trigger + workflow_dispatch) are unrecorded.

## E. Repo hygiene

- [ ] 6 stale upstream branches (gitbot, arc, revert-59-arc, shr, chore/dgxc-oss-policy-bootstrap, pull-request/388) + `feat/dashboard-enhancements` with no open PR.
- [ ] Issue #333 (helm cosign UNAUTHORIZED) is resolved by the helm-publish split + #388 — close it.

**Comment by ArangoGutierrez** [comment]
go-review pass over the v0.2.0 Go surface (mockib daemon/fabric/subnet/registry, mocknvml engine v0.2.0 files, imexcoord/fake-imex, codecs/renderers, thin binaries): 1 must-fix, 4 should-fix, 11 consider.

Must-fix:
- [ ] pkg/network/mockib/daemon/fabric.go:272 — sendRegister sets no I/O deadline; a peer that accepts but never reads wedges the sequential registerWithPeersLoop forever, silently stopping re-registration to all peers for the pod's life (pingPeer at :282 sets a deadline; this is the asymmetric miss).

Should-fix:
- [ ] daemon/server.go:313-331 — handleRecv busy-polls with client-controlled uncapped TimeoutMS and no ctx check; cap (~60s) and thread serveConn's ctx into the loop.
- [ ] daemon/fabric.go:144-147 — applyRegister logs every port on every 2s re-register (~86k lines/day in a 2-node CI fabric); have registry.Register return changed and log on change only.
- [ ] daemon/fabric.go:196-211 + daemon/discover.go:15 — registerWithPeers ignores ctx between peers post-SIGTERM; DiscoverPeerIPs uses net.LookupHost without ctx (use net.DefaultResolver.LookupHost(ctx, host)).
- [ ] sysfs/scan.go:42-49 — missing node_guid normalizes "" to "0000:0000:0000:0000" (non-empty), defeating fabric.coalesceGUID's fallback; all local ports then advertise a zero NodeGUID and ibnetdiscover-style consumers merge all CAs into one node. Guard the empty case before normalizing.

Consider items (11) include: SA PathRecord sniffing matches payload bytes without checking MgmtClass (daemon/sa.go:46-62); umadMADOffset/destLID duplicated across daemon and subnet; concurrent applyRegister snapshot->Build->store can publish an older graph (self-heals in 2s); errors.Is(syscall.ECONNREFUSED) instead of string match (daemon/fabric.go:246-257); bare returns in protocol/wire.go frame I/O; redundant double-alloc in subnet/synthesize.go:95-98; per-hop sorts in fabric/drpath.go on pre-sorted data; failure_injector.go:242-249 case-sensitive mode match silently coerces 'Lost' to healthy; production-code-only-used-by-tests saMethodResponseSet; scan.go and verbs.go error paths untested.

Everything else in scope reviewed clean (registry locking, engine dynamic_metrics/failure-injection atomics, imexcoord traversal defense, mockpcisysfs validation, thin binaries). Full review in session notes 2026-06-12.

**Comment by ArangoGutierrez** [comment]
v0.2.1 (tag 1275802b) closes a chunk of this issue:

- Go pins to 1.26.4 everywhere + kubectl v1.36.1 (17 CRITICAL/HIGH findings from that binary gone): #394
- tests/mocknvml harness build + GetHandleByUUID NOT_FOUND semantics (the nil-UUID default collision): #395
- mockib go-review must-fix and all four should-fixes: #396
- CHANGELOG gaps (0.2.0 retro entries, 0.2.1 section): #397; v0.2.0 release notes amended in place

Still open from the original list: sparse power-config N/A mapping, processes rendering (watch #381), make verify -w/vendor behavior, image cosign sign-by-digest, allow_force_pushes, base-image digest pins, actions/stale pin, REUSE globs, stale branches, gosec G115 triage.

New item from today's train:
- [ ] e2e-multi-node flakes on device-plugin pod readiness timeouts (timed out waiting for the condition on pods/nvidia-device-plugin-mock-*): hit 2 of 3 PRs today (runs 27410934213, 27411931475), both green on plain rerun with zero code changes. Likely needs a longer readiness timeout or wait-loop in the multi-node job.
