### ISSUE TITLE
CI lint skips all e2e-tagged files, hiding 4 existing issues

### ISSUE THREAD

**Issue by ArangoGutierrez** [NVIDIA/k8s-test-infra#510]
## Summary

`make lint` runs `golangci-lint run ./...` without build tags, so every file behind `//go:build e2e` is invisible to CI linting. Those files currently carry 4 issues that no gate reports.

Found during the Mokka + AICR pre-silicon preflight POC (2026-07-25).

## Evidence

```
$ golangci-lint run ./...
0 issues.

$ golangci-lint run --build-tags=e2e ./...
tests/e2e/go/report_skips_test.go:56:12: Error return value of `fmt.Fprint` is not checked (errcheck)
tests/e2e/go/scenario_failure_injection.go:12:2: ST1001: should not use dot imports (staticcheck)
tests/e2e/go/scenario_failure_injection.go:13:2: ST1001: should not use dot imports (staticcheck)
tests/e2e/go/scenario_runtime_control.go:14:2: ST1001: should not use dot imports (staticcheck)
4 issues:
* errcheck: 1
* staticcheck: 3
```

None of these are new, and none were introduced by #503. They have simply never been visible.

## Why it matters

The e2e harness is not incidental code. It is the thing that decides whether the mock works, and it is the substrate the AICR preflight composes with. Leaving it outside the lint gate means the least-reviewed code in the repo is also the least-checked.

The dot imports are arguably intentional: Ginkgo and Gomega are conventionally dot-imported, and `tests/e2e/go` does it consistently. That is a case for an exclusion, not for leaving the whole tag unlinted.

## What to do

1. Add `--build-tags=e2e` to the `lint` target in the `Makefile`.
2. Fix the errcheck finding (`report_skips_test.go:56`), which is a real if trivial miss.
3. Add a scoped `staticcheck` exclusion for `ST1001` under `tests/e2e/` in `.golangci.yml`, with a comment saying it is for the Ginkgo and Gomega DSL. Do not disable `ST1001` repo-wide.
4. Re-run and confirm zero issues under both tag sets.

Check `.golangci.yml` for an existing exclusions block before adding one; the repo may already have the right shape for this.

## Size

**S.**

## Acceptance

- `golangci-lint run --build-tags=e2e ./...` reports 0 issues.
- CI runs the lint with the tag, so a new e2e file cannot land unlinted.
